#pragma once

/**
 * @brief EEPROM address map.
 */
#define EE_ADDRESS_CONFIG_MAGIC (0x0030)

#define EE_ADDRESS_DISTANCESENSOR (0x0040)
#define EE_ADDRESS_GARAGECOVER (0x0060)
#define EE_ADDRESS_HEIGHTSENSOR (0x0080)
#define EE_ADDRESS_HUMIDITYSENSOR (0x00A0)
#define EE_ADDRESS_PRESENCEBINARYSENSOR (0x00C0)
#define EE_ADDRESS_TEMPERATURESENSOR (0x00E0)

/**
 * @brief Detailed EEPROM address map for GarageCover.
 */
#define EE_ADDRESS_CONFIG_GARAGECOVER_0 EE_ADDRESS_GARAGECOVER

/**
 * @brief Detailed EEPROM address map for DistanceSensor.
 */
#define EE_ADDRESS_CONFIG_DISTANCESENSOR_0 EE_ADDRESS_DISTANCESENSOR
#define EE_ADDRESS_CONFIG_DISTANCESENSOR_1 \
  (EE_ADDRESS_CONFIG_DISTANCESENSOR_0 + sizeof(DistanceT) + 1)
#define EE_ADDRESS_CONFIG_DISTANCESENSOR_2 \
  (EE_ADDRESS_CONFIG_DISTANCESENSOR_1 + sizeof(uint16_t) + 1)
#define EE_ADDRESS_CONFIG_DISTANCESENSOR_3 \
  (EE_ADDRESS_CONFIG_DISTANCESENSOR_2 + sizeof(uint16_t) + 1)

/**
 * @brief Detailed EEPROM address map for HeightSensor.
 */
#define EE_ADDRESS_CONFIG_HEIGHTSENSOR_0 EE_ADDRESS_HEIGHTSENSOR
#define EE_ADDRESS_CONFIG_HEIGHTSENSOR_1 \
  (EE_ADDRESS_CONFIG_HEIGHTSENSOR_0 + sizeof(HeightT) + 1)
#define EE_ADDRESS_CONFIG_HEIGHTSENSOR_2 \
  (EE_ADDRESS_CONFIG_HEIGHTSENSOR_1 + sizeof(uint16_t) + 1)
#define EE_ADDRESS_CONFIG_HEIGHTSENSOR_3 \
  (EE_ADDRESS_CONFIG_HEIGHTSENSOR_2 + sizeof(uint16_t) + 1)

/**
 * @brief Detailed EEPROM address map for HumiditySensor.
 */
#define EE_ADDRESS_CONFIG_HUMIDITYSENSOR_0 EE_ADDRESS_HUMIDITYSENSOR
#define EE_ADDRESS_CONFIG_HUMIDITYSENSOR_1 \
  (EE_ADDRESS_CONFIG_HUMIDITYSENSOR_0 + sizeof(HumidityT) + 1)
#define EE_ADDRESS_CONFIG_HUMIDITYSENSOR_2 \
  (EE_ADDRESS_CONFIG_HUMIDITYSENSOR_1 + sizeof(uint16_t) + 1)
#define EE_ADDRESS_CONFIG_HUMIDITYSENSOR_3 \
  (EE_ADDRESS_CONFIG_HUMIDITYSENSOR_2 + sizeof(uint16_t) + 1)

/**
 * @brief Detailed EEPROM address map for PrecenseBinarySensor.
 */
#define EE_ADDRESS_CONFIG_PRESENCEBINARYSENSOR_0 EE_ADDRESS_PRESENCEBINARYSENSOR
#define EE_ADDRESS_CONFIG_PRESENCEBINARYSENSOR_1 \
  (EE_ADDRESS_CONFIG_PRESENCEBINARYSENSOR_0 + sizeof(HeightT) + 1)
#define EE_ADDRESS_CONFIG_PRESENCEBINARYSENSOR_2 \
  (EE_ADDRESS_CONFIG_PRESENCEBINARYSENSOR_1 + sizeof(HeightT) + 1)
#define EE_ADDRESS_CONFIG_PRESENCEBINARYSENSOR_3 \
  (EE_ADDRESS_CONFIG_PRESENCEBINARYSENSOR_2 + sizeof(uint16_t) + 1)

/**
 * @brief Detailed EEPROM address map for TemperatureSensor.
 */
#define EE_ADDRESS_CONFIG_TEMPERATURESENSOR_0 EE_ADDRESS_TEMPERATURESENSOR
#define EE_ADDRESS_CONFIG_TEMPERATURESENSOR_1 \
  (EE_ADDRESS_CONFIG_TEMPERATURESENSOR_0 + sizeof(TemperatureT) + 1)
#define EE_ADDRESS_CONFIG_TEMPERATURESENSOR_2 \
  (EE_ADDRESS_CONFIG_TEMPERATURESENSOR_1 + sizeof(uint16_t) + 1)
#define EE_ADDRESS_CONFIG_TEMPERATURESENSOR_3 \
  (EE_ADDRESS_CONFIG_TEMPERATURESENSOR_2 + sizeof(uint16_t) + 1)
