; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pro8MHzatmega328]
platform = atmelavr
board = pro8MHzatmega328
framework = arduino
monitor_speed = 115200
lib_deps = 
	teckel12/NewPing@^1.9.7
	sandeepmistry/LoRa@^0.8.0
	robtillaart/CRC@^1.0.3
	rweather/Crypto@^0.4.0
	adafruit/Adafruit BusIO@^1.17.4
test_ignore = *

[env:native]
platform = native
test_framework = googletest
lib_deps = 
	google/googletest@^1.15.2
	robtillaart/CRC@^1.0.3
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit BusIO@^1.17.4
build_flags = 
	-std=c++17
	-I test/mocks/include
	-I.pio/libdeps/native/googletest/googlemock/include
	-I.pio/libdeps/native/googletest/googletest/include
	-DSKIP_DEATH_TESTS
build_src_filter = -<test/test_RingBuffer/>
test_ignore = test_old
build_type = debug
debug_test = test_GarageCover
debug_build_flags = -O0 -g3 -ggdb
