#pragma once

/**
 * @brief EEPROM address map.
 */
#define EE_ADDRESS_CONFIG_MAGIC (0x0030)
#define EE_ADDRESS_ITEM_SIZE (sizeof(uint32_t) + 1)  // Value size + CRC8

#define EE_ADDRESS_HEIGHT_SENSOR (0x0040)
#define EE_ADDRESS_PRESENCE_BINARY_SENSOR (0x0060)

/**
 * @brief Detailed EEPROM address map for HeightSensor.
 */
#define EE_ADDRESS_CONFIG_HEIGHT_SENSOR_0 EE_ADDRESS_HEIGHT_SENSOR
#define EE_ADDRESS_CONFIG_HEIGHT_SENSOR_1 \
  (EE_ADDRESS_CONFIG_HEIGHT_SENSOR_0 + EE_ADDRESS_ITEM_SIZE)

/**
 * @brief Detailed EEPROM address map for PresenceBinarySensor.
 */
#define EE_ADDRESS_CONFIG_PRESENCE_BINARY_SENSOR_0 \
  EE_ADDRESS_PRESENCE_BINARY_SENSOR
#define EE_ADDRESS_CONFIG_PRESENCE_BINARY_SENSOR_1 \
  (EE_ADDRESS_CONFIG_PRESENCE_BINARY_SENSOR_0 + EE_ADDRESS_ITEM_SIZE)
#define EE_ADDRESS_CONFIG_PRESENCE_BINARY_SENSOR_2 \
  (EE_ADDRESS_CONFIG_PRESENCE_BINARY_SENSOR_1 + EE_ADDRESS_ITEM_SIZE)
